# Generated by Django 5.0.7 on 2024-07-18 13:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = (
        ("finance", "0001_initial"),
    )

    operations = (
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["wallet"], name="finance_tra_wallet__1163cb_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["txid"], name="finance_tra_txid_a0cc88_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["amount"], name="finance_tra_amount_84277c_idx"),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["label"], name="finance_wal_label_152a6d_idx"),
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(fields=["balance"], name="finance_wal_balance_acdcb7_idx"),
        ),
    )
